apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/mohamed67471/umami-eks-project
    targetRevision: main
    path: applications/umami/helm
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: umami
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
